### ISSUE TITLE
Feature Request: GroupBy.rank

### ISSUE THREAD

**Issue by binshengliu** [EelcoHoogendoorn/Numpy_arraysetops_EP#22]
Hi, thanks for making the library. It's been an extremely useful tool for me.

I was just wondering if it's possible to have a vectorized GroupBy.rank which provides ranks within groups.

References:
- https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.GroupBy.rank.html
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rankdata.html

**Comment by EelcoHoogendoorn** [comment]
Hi;

```npi.group_by(npi.rank(keys)```

This is something you can do within npi; except that npi.rank does not do any tie-breaking; it gives every item in `keys` a unique rank, even tied values.

But if you want to group by rank, where tied values recieve the same rank, that should be identical to just grouping by the keys themselves, no?

Note that the conceptual model of npi is not the same as pandas; npi does not have a notion of a persistent table that we are adding properties to; its more of a functional model.

Perhaps if you give a higher level description of the task you are trying to solve, I could point out a more npi-ideomatic solution; or it might suggest natural future additions.

**Comment by binshengliu** [comment]
Hi,

Sorry I should have provided more context for this request. A more proper reference might be wikipedia: https://en.wikipedia.org/wiki/Ranking.

The request is a feature that assigns rank position within groups.

Let me try to use an example to demonstrate the problem. Say we have a search engine, and it is processing two queries: "java" and "c++". The search engine has many algorithms internally. One algorithm calculates scores for some "documents" and produces such data:

```
query,doc,score
java,doc1,0.5
java,doc2,0.3
java,doc3,0.6
c++,doc8,0.2
c++,doc7,0.1
c++,doc9,0.9
```

Let's say `keys` and `scores` are two variables that represent the first and last column.

What is desired is a corresponding rank (4th column) based on the scores within groups:

```
query,doc,score,rank
java,doc1,0.5,2
java,doc2,0.4,3
java,doc3,0.6,1
c++,doc8,0.1,3
c++,doc7,0.2,1.5      # special tie handling: average of 1 and 2
c++,doc9,0.2,1.5      # special tie handling: average of 1 and 2
```

The broader context of this type of operation is learning-to-rank which is a machine learning sub-field for search engines. For example, ranks are a feature of some search engine models; ranking is also performed at test time to produce the correct order for evaluation (absolute scores don't matter).

What I currently do to achieve this is
```
from scipy.stats import rankdata

g = npi.group_by(keys)

# Produce ranks of each group
ranks = [rankdata(arr=x, method="average") for x in g.split(scores)]

rank = np.hstack(ranks)

# Restore the original key order
rank = rank[g.index.sorter.argsort()]
```

This is not very elegant because of the for loop. So I was wondering if this can be done in a vectorized way. I've been thinking about it for a while but couldn't come up with a satisfactory solution. Any pointers would be very much appreciated.

**Comment by EelcoHoogendoorn** [comment]
Hi, thanks for the example, that makes sense.

First of all; let me reflect on some design decisions; npi intentionally does not have a notion of a dataframe. I created it exactly for those kind of use cases where itd be super annoying to have to cram your data into a dataframe and extract the column again just because you wanted to do a simple group-by reduction on an array. 

I somewhat hate to say it (I suppose in my opinion pandas is the worst excel replacement; except maybe for all the others that have been tried), but it sounds like the problem you are working could be of a kind where a dataframe-like abstraction might be useful to you. That being said for my own uses cases I do like to take an npi-based approach to its limits before I will `import pandas` and im not saying that wouldnt be viable here either.

```
def test_group_rank():
    gid = [0,1,0,1,0,1]
    val = [1,3,6,8,4,3]
    gidx = as_index(gid)
    c = np.cumsum(gidx.count) - gidx.count[0]
    rank_offset = c[gidx.inverse]
    rank_in_group = as_index((val, gid)).rank - rank_offset
    print(rank_in_group)
```
This seems like it does what you are looking for in a vectorized manner, modulo the tie-breaking? Might serve as a starting point. I imagine that numerically for most downstream numerical model-fitting purposes, the tie-breaking is kinda moot.

**Comment by binshengliu** [comment]
Thanks for sharing your thoughts on the design. I share pretty much the same idea. I try my best to avoid using pandas as an intermediate tool just for groupby functions. I also have a practical reason which is memory consumption. I sometimes process millions of rows and using pandas incurs too much memory overhead. Even if data fits in memory pandas.groupby is hardly efficient.

It's a bit unfortunate ties cause a lot of problems in this field, such as lack of reproducibility and improper evaluation. And because texts are discrete, ties happen more often than one would think especially if classic models are used. Without ties, ranking is simply argsort and can be vectorized as you suggested. But I have to admit I'm also simply bothered by the lack of a vectorized solution even if it causes no practical issues :). Your snippet does provide some new ideas. I'll probably give it another go.

**Comment by EelcoHoogendoorn** [comment]
Yeah indeed, pandas is a bit of a black box that can really explode in your face in terms of memory or runtime performance.

```
def test_group_rank():
    gid = [0,1,0,1,0,1]
    val = [1,3,6,8,4,3]
    gidx = as_index(gid)
    c = np.cumsum(gidx.count) - gidx.count[0]
    rank_offset = c[gidx.inverse]
    lexidx = as_index((val, gid))
    rank_in_group = lexidx.rank - rank_offset
    k, v = group_by(lexidx).mean(rank_in_group)
    tie_broken_rank_in_group = v[lexidx.inverse]
    print()
    print(rank_in_group)
    print(tie_broken_rank_in_group)
```
This should add tie-breaking; without really adding much additional overhead, since we can reuse the (val, gid) lex-index object to average over ranks with identical gid and val.

**Comment by binshengliu** [comment]
Love it. Using `(val, gid)` lex-index to handle ties is brilliant! Do you think this is something that can be built into npi?

**Comment by EelcoHoogendoorn** [comment]
Happy to help; not sure I have the overview to carve out a sufficiently general pattern yet that would justify that effort... nor do I have a lot of bandwidth to work on this. But if you want to work it out and submit a PR, i am happy to consider it.

**Comment by binshengliu** [comment]
That's all good. I'll probably use it for a while and see if I'll be able to put together a PR. Thanks again for the help. I'll close it for now.
